sudo: required
services:
  - docker

before_install:
  - docker build -t troy/react-test -f ./reactclient/Dockerfile.dev ./reactclient

script:
  - docker run troy/react-test npm test

after_success:
  - docker build -t tbiddu/multinginx ./nginx
