version: '3'
services:
  postgres:
    image: 'postgres:latest'
  
  redis:
    image: 'redis:latest'

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    
    volumes:
      - /app/node_modules
      - ./server:/app

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DATABASE=postgres
      - PG_USERNAME=postgres
      - PG_PASSWORD=postgres_password
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    
    volumes:
      - /app/node_modules
      - ./client:/app
    
    
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    
    volumes:
      - /app/node_modules
      - ./worker:/app
    
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  
  
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'